# Generated by Django 2.2 on 2021-12-24 19:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('ref', models.CharField(max_length=8, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(
                    '^[0-9a-zA-z]{8}$', 'Candidate Reference should be a unique string of 8 letters and digits')])),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('candidate', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='scoring.Candidate')),
            ],
        ),
    ]
